name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
       fetch-depth: 0
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Publish to Maven Local
      run: ./gradlew build publishToMavenLocal --stacktrace -PlocalPublish
    - uses: actions/upload-artifact@v2
      with:
        name: Maven
        path: ~/.m2/
      
  test_examples:
    needs: build
    runs-on: ubuntu-latest
    strategy:
     matrix:
        language: [cpp, java, jni, kotlin]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/download-artifact@v2
      with:
        name: Maven
        path: ~/.m2/
     
    - name: Setup RoboRIO Toolchain
      if: ${{ (matrix.language == 'cpp') || (matrix.language == 'jni') }}
      run: ./gradlew installRoboRioToolchain
      working-directory: examples/${{ matrix.language }}
    - name: Test ${{ matrix.language }} Build
      run: ./gradlew build
      working-directory: examples/${{ matrix.language }}
     
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.language }}
        path: examples/${{ matrix.language }}/build/
