name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2020-18.04
    steps:
    - uses: actions/checkout@v2
      with:
       fetch-depth: 0
    - name: Publish to Maven Local
      run: ./gradlew build publishToMavenLocal --stacktrace -PlocalPublish
    - uses: actions/upload-artifact@v2.2.0
      with:
        name: Maven
        path: build/distributions
      
  test_examples:
    needs: build
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2020-18.04
    strategy:
     matrix:
        language: [cpp, java, jni, kotlin]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2.0.5
      with:
        name: Maven
        path: $USER_HOME/.m2/repository
     
    - name: Test ${{ matrix.language }} Build
      run: ./gradlew build
      working-directory: examples/${{ matrix.language }}
     
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.language }}
        path: build/distributions
