name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2020-18.04
    steps:
    - uses: actions/checkout@v2
       with:
         fetch-depth: 0
    - name: Publish to Maven Local
      run: ./gradlew build publishToMavenLocal PatchExamples --stacktrace -PlocalPublish
      
      
    - name: Test Cpp Build
      run: ./gradlew build
      working-directory: examples/cpp
        
    - name: Test Java Build
      run: ./gradlew build
      working-directory: examples/java
        
        
    - name: Test JNI Build
      run: ./gradlew build
      working-directory: examples/jni
        
    - name: Test Kotlin Build
      run: ./gradlew build
      working-directory: examples/kotlin
        
    - uses: actions/upload-artifact@v2
      with:
        name: Examples
        path: build/distributions
