name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2020-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
       with:
         fetch-depth: 0
    - name: Publish to Maven Local
      run: |
        chmod +x gradlew
        ./gradlew -Xmx3072m build publishToMavenLocal PatchExamples --stacktrace -PlocalPublish
      
      
    - name: Test Cpp Build
      run: |
        cd examples/cpp
        chmod +x ./gradlew
        ./gradlew build
        
    - name: Test Java Build
      run: |
        cd examples/java
        chmod +x ./gradlew
        ./gradlew build
        
        
    - name: Test JNI Build
      run: ./gradlew build
      working-directory: examples/jni
        
    - name: Test Kotlin Build
      run: |
        cd examples/kotlin
        chmod +x ./gradlew
        ./gradlew build
        
    - uses: actions/upload-artifact@v2
      with:
          name: "Examples"
