name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2020-18.04
    steps:
    - uses: actions/checkout@v2
      with:
       fetch-depth: 0
    - name: Publish to Maven Local
      run: ./gradlew build publishToMavenLocal --stacktrace -PlocalPublish
    - name: Test (delete this)
      run: |
        ls -R ~
        mkdir -p MyArtifacts
        cp -r ~/.m2/repository/* MyArtifacts
        ls MyArtifacts
    - uses: actions/upload-artifact@v2.2.0
      with:
        name: Maven
        path: MyArtifacts
      
  test_examples:
    needs: build
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2020-18.04
    strategy:
     matrix:
        language: [cpp, java, jni, kotlin]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2.0.5
      with:
        name: Maven
        path: ~/.m2/
     
    - name: Test ${{ matrix.language }} Build
      run: ./gradlew build
      working-directory: examples/${{ matrix.language }}
     
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.language }}
        path: examples/${{ matrix.language }}/build/
